### ISSUE TITLE
pip dependencies conflicting error

### ISSUE THREAD

**Issue by caiomts** [tiangolo/typer-cli#118]
Hi,
I tried to update Typer to 0.8.0 in a personal project where I use both (Typer and Typer-cli) and I got a pip dependencies conflicting error as follows:

The conflict is caused by:
      The user requested typer<0.9 and >=0.8.0
      typer-cli 0.0.13 depends on typer <=0.7.0 and >=0.4.0

Hope the Error is just a matter of updating the pyproject.toml.

**Comment by xyxz-web** [comment]
Seems like there is not much love for typer-cli.
We are at typer 0.9.0 and typer-cli still only supports 0.7.0.
I wonder why typer-cli is still advertised in the typer docs when you can't actually use it with its current versions.

**Comment by andreportela** [comment]
I did hit that wall. I installed typer (0.9.0) first and now I cannot install typer-cli =)

**Comment by tiangolo** [comment]
Hello! Now Typer-CLI is included in Typer, so, you no longer need to install `typer-cli`, just install `typer` and you get the `typer` command and everything.

This means the versions, the code, everything, are always in sync and supported. :rocket: 

This is since Typer version `0.12.1`. Now this repo, `typer-cli`, is no longer needed. :nerd_face:
