### ISSUE TITLE
Support for `typer==0.9.0`

### ISSUE THREAD

**Issue by liblaf** [tiangolo/typer-cli#125]
The latest `typer-cli==0.0.13` requires `typer >=0.4.0,<=0.7.0`, which is not compatible with the latest `typer==0.9.0`.

**Comment by jeremyjordan** [comment]
#120 fixes this, though it needs approval

**Comment by PieterBunnenberg** [comment]
I created a discussion for this issue: https://github.com/tiangolo/typer-cli/discussions/134

**Comment by tiangolo** [comment]
Thank you! Now `typer-cli` is part of the main `typer` repo, when you install with `pip install typer` you get the `typer` command with all the functionality. :tada: 

This is since Typer 0.12.1 :nerd_face: 

That means that now there's only one dependency, `typer`, and the versions and code are always in sync, because everything is there. :rocket:
